<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25954" started-at="2018-01-04T11:32:01Z" finished-at="2018-01-04T11:32:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25954" started-at="2018-01-04T11:32:01Z" finished-at="2018-01-04T11:32:27Z">
      <class name="com.test.automation.TimeDoctorLogin.loginpage.TC001_VerifyLoginWithInvalidCradential">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.test.automation.TimeDoctorLogin.loginpage.TC001_VerifyLoginWithInvalidCradential@f777e8]" name="setup" is-config="true" duration-ms="21983" started-at="2018-01-04T17:02:01Z" finished-at="2018-01-04T17:02:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="VerifyLoginWithInvalidCradential()[pri:0, instance:com.test.automation.TimeDoctorLogin.loginpage.TC001_VerifyLoginWithInvalidCradential@f777e8]" name="VerifyLoginWithInvalidCradential" duration-ms="2885" started-at="2018-01-04T17:02:23Z" finished-at="2018-01-04T17:02:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.test.automation.TimeDoctorLogin.uiAction.LoginPage.getInvalidTextMessage(LoginPage.java:59)
	at com.test.automation.TimeDoctorLogin.loginpage.TC001_VerifyLoginWithInvalidCradential.VerifyLoginWithInvalidCradential(TC001_VerifyLoginWithInvalidCradential.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginWithInvalidCradential -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.test.automation.TimeDoctorLogin.loginpage.TC001_VerifyLoginWithInvalidCradential@f777e8]" name="endTest" is-config="true" duration-ms="1061" started-at="2018-01-04T17:02:26Z" finished-at="2018-01-04T17:02:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.test.automation.TimeDoctorLogin.loginpage.TC001_VerifyLoginWithInvalidCradential -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
